# Generated by Django 5.0.4 on 2024-06-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="thumbnail",
            field=models.BooleanField(default=False),
        ),
    ]
