# Generated by Django 5.0.4 on 2024-06-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_id_alter_product_quantity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
