# Generated by Django 5.0.4 on 2024-06-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_delete_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_img",
            field=models.ImageField(blank=True, upload_to="products"),
        ),
    ]
